#!/bin/bash

fio --name=mango_fio \
    --filename=/dev/sdb \
    --ioengine=libaio \
    --rw=randwrite \
    --bs=8k \
    --size=240G \
    --numjobs=1 \
    --iodepth=32 \
    --direct=1 \
    --invalidate=0 \
    --runtime=10s \
    --time_based \
    --group_reporting
